### ISSUE TITLE
Dataset api not working properly

### ISSUE THREAD

**Issue by MikeyBeLike** [patrickkunka/mixitup#267] opened 2016-12-16 07:30 UTC
So from my understanding rather than manipulating the dom with using sort/insert etc

I got from this line:

"We believed that in the right circumstances however, developers should be able control MixItUp directly via changes to their application data model, and bypass the uglyness of working with the DOM directly."

That you can simply update the data model and that will be reflected in the dom.

Now this kind of works for me.. But it only works on the first update, updates after that seem to fail.

See jsfiddle here:

https://jsfiddle.net/Samus/68up9rbt/

Am I doing something wrong here?

**Comment by patrickkunka** [comment] 2016-12-16 09:38
Hi Lyricalz,

This does appear to be an issue with the dirtyCheck feature. There seems to be a second issue related to the animation queue and dataset.

I will look into both of these and try to get a patch out asap.

**Comment by patrickkunka** [comment] 2016-12-16 11:22
Hi again,

These issues have now been fixed in v3.1.1

Here's a fully working modified version of your original fiddle:

https://jsfiddle.net/68up9rbt/2/

Please let me know if you continue to have issues.

**Comment by MikeyBeLike** [comment] 2016-12-17 17:07
Awesome thanks!

**Comment by MikeyBeLike** [comment] 2017-01-06 11:23
Hey again,

I'm once again facing issues with this, see fiddle:

https://jsfiddle.net/Samus/68up9rbt/

If you run the buttons one by one, you get expected results.. But if you try to immediately run the 'Update' button, then you get the same issue that was happening before. 

basically it still isn't really taking a completely new dataset and performing the appropriate updates/sorting/inserting etc

**Comment by nth-alex** [comment] 2017-01-06 19:33
Hi. I'm trying to load data from API via jQuery AJAX and dataset method, but it render data only at first call. I'm receiving new data from API, pass it to the dataset() and it won't update.
Here is my code:
```javascript
var post_type = 'styles',
taxonomy = 'type',
button = $('button.filter'),
container = document.querySelector('[data-ref="container"]'),
term = '';


var mixer = mixItUp(container, {
  selectors: {
    target: '[data-ref="item"]' // Query targets with an attribute selector to keep our JS and styling classes seperate
  },
  data: {
    uidKey: 'id' // Our data model must have a unique id. In this case, its key is 'id'
  },
  render: { // We must provide a target render function incase we need to render new items not in the initial dataset (not used in this demo)
    target: function(item) {
      
      var link = item.link,
      thumb = item.better_featured_image.media_details.sizes["style-thumb"].source_url,
      alt = item.better_featured_image.alt_text,
      title = item.title.rendered;
      
      return '<li><a href="'+link+'"><img src="'+thumb+'" alt="'+alt+'"/><span class="style-title">'+title+'</span></a></li>';
    }
  }
});

function load_items(term) {
  var url = 'http://' + window.location.host + '/wp-json/wp/v2/' + post_type + '?filter['+taxonomy+']=' + term;

  $.ajax({
    url: url,
    success: function (items) {
      
      mixer.dataset(items)
      .then(function(state) {
        console.log(state);
      });
      
    }
  });
}

load_items(term);

// filter button
button.click(function () {
  var s = $(this);
  load_items( s.data('category') );
});
```

**Comment by patrickkunka** [comment] 2017-01-07 20:28
@Lyricalz Thanks for the fiddle that was very helpful. The issues were related to simultaneous sorting/inserting/dirty-checking, and should now be fixed in [v3.1.5](https://github.com/patrickkunka/mixitup/releases/tag/v3.1.5). The CDN referenced in your fiddle has been updated, and it appears to be working as intended now.

@ninjakvas One thing I can see is that the HTML string returned by your `render.target` function does not match your specified `selectors.target` selector. 

It should be:
```html
<li data-ref="item"><a href="... ></a></li>
```

I'm afraid I can't tell much else without seeing your data model or testing the full lifecycle of an API call. If you could provide a jsfiddle reproduction of your issue that would help. You could use an array literal to represent your returned data to keep things simple (as @Lyricalz did in his fiddle).

**Comment by MikeyBeLike** [comment] 2017-01-07 21:00
@patrickkunka that's much appreciated! Thank you for the fast turn around!

**Comment by nth-alex** [comment] 2017-01-09 11:43
@patrickkunka That was it. I missed **data-ref="item"**. Now all works fine. Thank you very much for your help!

**Closed as completed** 2017-01-09 12:23 UTC
