### ISSUE TITLE
Select Multiple with MultiFilter

### ISSUE THREAD

**Issue by juliocorral** [patrickkunka/mixitup#290] opened 2017-02-17 16:31 UTC
Hi!

I'm trying to use MixItUp Multifilter with one project. You can see it here:
http://www.casamytea.com/es/categorias/pagina_1/4/tes-e-infusiones/negro.php

But when I use a multiple select dropdown filter fails. Show the correct items for a while but then the last choice items disappears.

Could you help me? Thank you in advance.

On iMac I notice this effect when you use CMD+Click or SHIFT+Click to select two or more consecutive or non-consecutive options on multi-select. If you use MOUSE DOWN to select two or more consecutive options 
The elements work correctly. ???

**Comment by patrickkunka** [comment] 2017-02-17 21:14
Hi @juliocorral,

Thanks for spotting this bug and for the information and link.

This was caused by the extension mistakenly handling keyup events from all inputs instead of just textual inputs. Releasing the meta key after a multiselect gesture was being mistakenly treated as a user input.

This has now been fixed in v3.2.1 which you can download from your account. Please let me know if everything is now working as expected.

**Closed as completed by patrickkunka** 2017-02-17 21:14 UTC

**Comment by juliocorral** [comment] 2017-02-20 09:57
Hi, Patrick

Now is working right. THANK YOU!!!

Do you know if is possible to use your fantastic plugin with bootstrap
select? I'm trying to use it but when I try to combine both plugins all the
select options are lost.
You can see this here: http://www.casamytea.com/es/categorias/pagina_1/4/
tes-e-infusiones/negro.php

There are two select one is a normal select and second select is using
bootstrap select plugin and his options value are gone.

Thank you in advance.

2017-02-17 22:14 GMT+01:00 Patrick Kunka <notifications@github.com>:
