### ISSUE TITLE
Set search val from cookie to filter

### ISSUE THREAD

**Issue by konsumkuenstler** [patrickkunka/mixitup#524] opened 2019-10-25 16:14 UTC
Hi Patrick,

Im using Multifilter with several filters and store each values in a cookie. After reloading the page I read the cookie-values and load them in setFilterGroupSelectors. Everything works nice so far. 

But if the search-value is incomplete the filter throws an error. How can I achieve that 'Gree' still show any targets with the class 'green'?

Best

**Comment by patrickkunka** [comment] 2019-12-15 23:00
Hi @konsumkuenstler - sorry for the late response. Have you tried making your group selector (for the search input group) a partial selector?

e.g.: `[class^=gree]` instead of `.gree`?

**Comment by konsumkuenstler** [comment] 2019-12-16 10:19
Hi Patrick,
no problem and thanks for your reply. Im not sure if I understand you right. If I type "gree" im my searchfield, all elements with ".green" gets displayed. Now "gree" is the value which is stored in a cookie. After refreshing the page I check for the cookie and set it to the mixer:
mixer.setFilterGroupSelectors('color', mysearchvalue); If the value is "gree" the mixer doesnt load ".green" elements again.

**Comment by patrickkunka** [comment] 2020-01-05 20:38
Yeah that makes sense. I assume the issue is because your variable `mysearchvalue` is being stored as a class name selector e.g. `.gree` - which will only exactly match `class="gree"` in your HTML – not `class="green"`.

This will approach will work for all other input types apart from search inputs, which must use partial attribute selectors instead, which allow for partial matches: e.g. `[class^=gree]`.

See https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#Syntax for more info.

I recommend adjusting your code so that when you call `mixer.setFilterGrouPSelectors(...)` for the search input group, the search value is in the above format.

**Comment by patrickkunka** [comment] 2020-02-02 20:50
Closing for now, but let me know if you want me to reopen.

**Closed as completed by patrickkunka** 2020-02-02 20:50 UTC
