### ISSUE TITLE
[MixItUp MultiFilter] Not Working on iOS

### ISSUE THREAD

**Issue by timselay** [patrickkunka/mixitup#471] opened 2018-10-14 15:00 UTC
Hello Everyone,

Just implemented MixItUp Multifilter on my project and it works like a charm on desktop browsers : 
https://www.masterthehandpan.com/mix-it-up-handpan-makers-directory

**BUT it does NOT work on iOS Browsers.**
Attached 2 screen shots where you'll see the errors I get on Safari or Chrome
- Safari : This web page was reloaded because an error occured
- Chrome : Something went wrong...

Any idea of what's going on ?
Any help would be really appreciated

Thank you

![img_1961](https://user-images.githubusercontent.com/44139491/46918355-a64d5300-cfd1-11e8-931e-764284e66788.jpg)

![img_1960](https://user-images.githubusercontent.com/44139491/46918356-ab120700-cfd1-11e8-9a75-0313d6ef8046.jpg)

**Comment by patrickkunka** [comment] 2018-10-14 18:15
Hi, thanks for the info.

Does this happen when you first load the page, or after some specific interaction?

**Comment by timselay** [comment] 2018-10-14 18:40
No, right after loading the page.

Note : this bug doesn’t appear on android phones

**Comment by timselay** [comment] 2018-10-18 21:56
Any ideas ? Help :)

**Comment by ghost** [comment] 2018-10-19 07:56
I'm afraid I've been unable to recreate the issue on any device (including iOS safari and chrome).

Are you certain that the issue is related to MixItUp?

- Have you tested the multifilter demos on your ios device? If so, do you see the same error when loading the page?
- Have you tried removing MixItUp from your page, and observing whether the error still occurs?

**Comment by timselay** [comment] 2018-10-19 10:39
Thanks Patrick for the follow up.
So I transferred the test page to a blank one in order to make sure there would be no interaction with any other element. 

**Here is the URL : https://www.masterthehandpan.com/mixitup**

To answer your questions :  
- removing MixitUp makes the page functional with no errors
- yes, testing it right into my iPhone directly ( on a desktop browser with mobile view, it's working great)

But from what I can see, the error is not always displaying. 
Sometimes filters are doing their job as expected, sometimes it makes the page crash. Tested on different select fields to see if it was related to a certain select tags but it seems not. Sometimes a select field will work, sometimes not.

This could lead to think it's a hosting problem... but why would it be problematic only on iOS, and NEVER occur on desktop anyway...

**Comment by ghost** [comment] 2018-10-19 10:59
This might be unrelated but I was looking at your JS:

<img width="413" alt="screen shot 2018-10-19 at 11 53 59" src="https://user-images.githubusercontent.com/35066728/47214445-d9a72d80-d395-11e8-8c38-3e8684e9688e.png">

And I can see you're using some functionality from the select filtering demo for mixitup core. You actually don't need this if you're using the multifilter extension, as all of this logic and binding is done internally. You would still need the "sorting" part of it if you had a sort select, but duplicating filtering part could cause conflicts. 

Also - even in your stripped down page, looking at the JS network tab - you still have a lot of other scripts loaded and other functionality present:

<img width="304" alt="screen shot 2018-10-19 at 11 54 27" src="https://user-images.githubusercontent.com/35066728/47214522-1a06ab80-d396-11e8-8ac0-33025a4f158a.png">

It might be a good idea to create a simple static html page with __just__ your mixitup functionality on it and test against that - or maybe use one of the demos as I suggested before. Checkout /demos/selects/ in the multifilter package. If that works fine, then start adding in other functionality until we can be sure exactly what is causing the page to crash.

**Comment by timselay** [comment] 2018-10-19 12:24
Patrick first of all, thanks for helping me. 
Really appeciate it since I'm not a developper, I pretty much entirely depend on your good will ahah.

So I followed your recommandations : 
- Removed unnecessary lines of code (it was based on a webflow tutorial)
- Removed all .js files
- Removed the sorting selector (not the select field, but any code related to it)
- Extracted the page from its CMS so I can have a simple HTML to work on.

**Here is the file : https://blog.masterthehandpan.com/mixitup-nojs.html**
(sorry for changing again the URL... )

The good news is : much simpler to work on this file and understand the problem
The bad news : even in it's most simple form, testing it on iOS make it crash...

**Comment by ghost** [comment] 2018-10-19 12:38
Ah great - that's *really* helpful. I can't promise anything - but I'm keen to identify whether or not this is an issue with MixItUp or your specific integration, I just need to find a device where I can reproduce it first. This is a great starting point though.

Could you let me know the model of your iPhone and the version of iOS you're running?

**Comment by timselay** [comment] 2018-10-19 13:27
I'm on an iPhone X, on iOS 12.0

So, thanks to your method, by stripping down the code, I think I spotted an html error which I just corrected (on the countries select field) : 

https://blog.masterthehandpan.com/mixitup-nojs.html

Since then, I can't make the page crash, which is a good news.

When I correct this error in the CMS website it keeps crashing though...

So it might be some sort of an integration problem when importing into webflow. The problem is I can't pick and choose which js I want in a specific page...

2 questions :
- is there a known issue with some js files ?
- why would it crash ONLY on iOS, considering desktop is working fine

Thanks !

**Comment by patrickkunka** [comment] 2018-10-20 09:29
This would be easier to debug if there was an actual error thrown that we could see in the console, but this kind of "crashing" behaviour where the browser actulaly gives up and has to terminate a tab is usually an indication of a long running script, accidental infinite loop, or memory leak. If you are able to run your "nojs" page without crashing, then that would indicate that mixitup is not the issue, but rather something in your custom javasript (your integration), or something that webflow is adding. It is more likely to be the former.

In terms of why its only crashing on iOS, I don't really have an idea other than that iOS might be more aggresive about terminating a tab due to the types of issues I described above.

Also, could it be possible that now that you've fixed it on the "nojs" page, that the issue might just be that webflow still has the old version cached somehow? Are you able to determine that webflow has picked up your latest changes?

**Comment by patrickkunka** [comment] 2018-10-20 09:56
I thought I'd look further in to the memory leak issue by running the memory profiler in Chrome dev tools. I didn't find anything critical - but just to show you, the comparison:

In you're standard webflow setup, you have a lot of stuff going on on the page, and a few big initial spikes that could cause a browser to crash. In total the page is using about 7MB of memory:

<img width="742" alt="full-page-profile" src="https://user-images.githubusercontent.com/1686556/47254119-695fe100-d455-11e8-9b1d-edbbfe90f984.png">

I've drawn a box around where MixItUp sits relative to everything else on your page (it's using about 180KB in total).

I then ran another profile on your "nojs" page, where only mixitup is present:

The page is using only 1.6MB of memory now, and there are no spikes or long call stacks that could cause a crash. In case you're wondering the other stuff is just the normal background memory usage of V8.

<img width="742" alt="screen shot 2018-10-20 at 10 37 51" src="https://user-images.githubusercontent.com/1686556/47254145-be9bf280-d455-11e8-85ec-ed7f1fadc770.png">

Based on this, my best bet is that your issue is a memory leak caused by one of these big spikes shown on the first profile. The 3 worst offenders for memory usage are:

- `client.js` (and something called `Crisp` internally?) Spiking at around 600KB
- `webflow.dccbef211.js`, spking at around 500KB
- `addthis_widget.js`, spiking at around 700KB

I'm not the best at interpreting these profiles, but I think its fair to say there are more serious issues on the page.

As I don't think this is related to MixItUp, I'm going to close this ticket now. Apologies I couldn't be of more help, but hopefully this can point you in the right direction of being able to optimise your page.

**Closed as completed by patrickkunka** 2018-10-20 09:56 UTC
